### ISSUE TITLE
0.1.26: test suite fails with core dump

### ISSUE THREAD

**Issue by kloczek** [hughsie/colord-gtk#6] opened 2019-05-07 17:06 UTC
<pre>+ /usr/bin/make -O -j4 check
Making check in man
make[1]: Nothing to be done for &apos;check&apos;.
Making check in contrib
make[1]: Nothing to be done for &apos;check&apos;.
Making check in libcolord-gtk
/usr/bin/make  cd-self-test
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -I/usr/include/colord-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I.. -I../libcolord-gtk -DCD_COMPILATION -DG_LOG_DOMAIN=\&quot;libcolord-gtk\&quot; -DTESTDATADIR=\&quot;&quot;../data/tests&quot;\&quot; -DPACKAGE_DATA_DIR=\&quot;&quot;/usr/share&quot;\&quot; -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0   -Wall -Wcast-align -Wno-uninitialized -Wmissing-declarations -Wpointer-arith -Wcast-align -Wwrite-strings -Winit-self -Wreturn-type -Wformat-nonliteral -Wformat-security -Wmissing-include-dirs -Wmissing-format-attribute -Wclobbered -Wempty-body -Wignored-qualifiers -Wsign-compare -Wtype-limits -Wuninitialized -Waggregate-return -Wdeclaration-after-statement -Wshadow -Wno-strict-aliasing -Winline -Wmissing-parameter-type -Woverride-init -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -c -o cd_self_test-cd-self-test.o `test -f &apos;cd-self-test.c&apos; || echo &apos;./&apos;`cd-self-test.c
cd-self-test.c: In function &apos;main&apos;:
cd-self-test.c:122:2: warning: &apos;g_type_init&apos; is deprecated [-Wdeprecated-declarations]
  122 |  g_type_init ();
      |  ^~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/colord-1/colord/cd-client.h:29,
                 from /usr/include/colord-1/colord.h:38,
                 from cd-self-test.c:24:
/usr/include/glib-2.0/gobject/gtype.h:688:23: note: declared here
  688 | void                  g_type_init                    (void);
      |                       ^~~~~~~~~~~
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
/bin/sh ../libtool  --tag=CC   --mode=link gcc -Wall -Wcast-align -Wno-uninitialized -Wmissing-declarations -Wpointer-arith -Wcast-align -Wwrite-strings -Winit-self -Wreturn-type -Wformat-nonliteral -Wformat-security -Wmissing-include-dirs -Wmissing-format-attribute -Wclobbered -Wempty-body -Wignored-qualifiers -Wsign-compare -Wtype-limits -Wuninitialized -Waggregate-return -Wdeclaration-after-statement -Wshadow -Wno-strict-aliasing -Winline -Wmissing-parameter-type -Woverride-init -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o cd-self-test cd_self_test-cd-self-test.o -lcolord -lgio-2.0 -lgobject-2.0 -lglib-2.0  -pthread -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lpixman-1 -lfontconfig -lfreetype -lpng16 -lz -lxcb-shm -lxcb -lxcb-render -lXrender -lX11 -lXext -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  libcolord-gtk.la 
libtool: link: gcc -Wall -Wcast-align -Wno-uninitialized -Wmissing-declarations -Wpointer-arith -Wcast-align -Wwrite-strings -Winit-self -Wreturn-type -Wformat-nonliteral -Wformat-security -Wmissing-include-dirs -Wmissing-format-attribute -Wclobbered -Wempty-body -Wignored-qualifiers -Wsign-compare -Wtype-limits -Wuninitialized -Waggregate-return -Wdeclaration-after-statement -Wshadow -Wno-strict-aliasing -Winline -Wmissing-parameter-type -Woverride-init -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o .libs/cd-self-test cd_self_test-cd-self-test.o -pthread  ./.libs/libcolord-gtk.so -lcolord -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lpixman-1 -lfontconfig -lfreetype -lpng16 -lz -lxcb-shm -lxcb -lxcb-render -lXrender -lX11 -lXext -lgdk_pixbuf-2.0 -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -pthread
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
/usr/bin/make  check-TESTS
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
../test-driver: line 107: 23252 Aborted                 (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
FAIL: cd-self-test
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
============================================================================
Testsuite summary for colord-gtk 0.1.26
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See libcolord-gtk/test-suite.log
Please report to http://hughsie.com
============================================================================
make[3]: *** [Makefile:1146: test-suite.log] Error 1
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk&apos;
make[2]: *** [Makefile:1254: check-TESTS] Error 2
make[1]: *** [Makefile:1328: check-am] Error 2
make: *** [Makefile:522: check-recursive] Error 1
</pre>

**Comment by kloczek** [comment] 2019-05-07 17:07
<pre>[tkloczko@domek libcolord-gtk]$ cat test-suite.log 
=====================================================
   colord-gtk 0.1.26: libcolord-gtk/test-suite.log
=====================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: cd-self-test
==================

/colord/window: **
libcolord-gtk:ERROR:cd-self-test.c:45:cd_window_get_profile_cb: assertion failed (error == NULL): no device with that property: property match &apos;XRANDR_name&apos;=&apos;unknown&apos; does not exist (cd_window_error, 0)
FAIL cd-self-test (exit status: 134)

</pre>

**Comment by kloczek** [comment] 2019-05-07 17:08
<pre>[tkloczko@domek libcolord-gtk]$ sh -x ./cd-self-test
+ sed_quote_subst=&apos;s|\([`&quot;$\\]\)|\\\1|g&apos;
+ test -n &apos;&apos;
+ case `(set -o) 2&gt;/dev/null` in
+ set -o posix
+ BIN_SH=xpg4
+ export BIN_SH
+ DUALCASE=1
+ export DUALCASE
+ unset CDPATH
+ relink_command=&apos;(cd /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk; { test -z &quot;${LIBRARY_PATH+set}&quot; || unset LIBRARY_PATH || { LIBRARY_PATH=; export LIBRARY_PATH; }; }; { test -z &quot;${COMPILER_PATH+set}&quot; || unset COMPILER_PATH || { COMPILER_PATH=; export COMPILER_PATH; }; }; { test -z &quot;${GCC_EXEC_PREFIX+set}&quot; || unset GCC_EXEC_PREFIX || { GCC_EXEC_PREFIX=; export GCC_EXEC_PREFIX; }; }; { test -z &quot;${LD_RUN_PATH+set}&quot; || unset LD_RUN_PATH || { LD_RUN_PATH=; export LD_RUN_PATH; }; }; { test -z &quot;${LD_LIBRARY_PATH+set}&quot; || unset LD_LIBRARY_PATH || { LD_LIBRARY_PATH=; export LD_LIBRARY_PATH; }; }; PATH=/usr/bin:/usr/sbin:/usr/local/sbin; export PATH; gcc -Wall -Wcast-align -Wno-uninitialized -Wmissing-declarations -Wpointer-arith -Wcast-align -Wwrite-strings -Winit-self -Wreturn-type -Wformat-nonliteral -Wformat-security -Wmissing-include-dirs -Wmissing-format-attribute -Wclobbered -Wempty-body -Wignored-qualifiers -Wsign-compare -Wtype-limits -Wuninitialized -Waggregate-return -Wdeclaration-after-statement -Wshadow -Wno-strict-aliasing -Winline -Wmissing-parameter-type -Woverride-init -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o $progdir/$file cd_self_test-cd-self-test.o -pthread  ./.libs/libcolord-gtk.so -lcolord -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lpixman-1 -lfontconfig -lfreetype -lpng16 -lz -lxcb-shm -lxcb -lxcb-render -lXrender -lX11 -lXext -lgdk_pixbuf-2.0 -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -pthread -Wl,-rpath -Wl,/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs)&apos;
+ test &apos;&apos; = &apos;%%%MAGIC variable%%%&apos;
+ test &apos;&apos; &apos;!=&apos; &apos;%%%MAGIC variable%%%&apos;
+ file=./cd-self-test
+ ECHO=&apos;printf %s\n&apos;
+ lt_option_debug=
+ func_parse_lt_options ./cd-self-test
+ lt_script_arg0=./cd-self-test
+ shift
+ test -n &apos;&apos;
++ printf &apos;%s\n&apos; ./cd-self-test
++ /usr/bin/sed &apos;s%/[^/]*$%%&apos;
+ thisdir=.
+ test x. = x./cd-self-test
++ ls -ld ./cd-self-test
++ /usr/bin/sed -n &apos;s/.*-&gt; //p&apos;
+ file=
+ test -n &apos;&apos;
+ WRAPPER_SCRIPT_BELONGS_IN_OBJDIR=no
+ test no = yes
++ cd .
++ pwd
+ absdir=/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk
+ test -n /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk
+ thisdir=/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk
+ program=lt-cd-self-test
+ progdir=/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs
+ test &apos;!&apos; -f /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
++ ls -1dt /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/../lt-cd-self-test
++ /usr/bin/sed 1q
+ file=/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
+ test X/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test &apos;!=&apos; X/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
+ test -f /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
+ test &apos;&apos; &apos;!=&apos; &apos;%%%MAGIC variable%%%&apos;
+ func_exec_program
+ case &quot; $* &quot; in
+ func_exec_program_core
+ test -n &apos;&apos;
+ exec /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
/colord/window: **
libcolord-gtk:ERROR:cd-self-test.c:45:cd_window_get_profile_cb: assertion failed (error == NULL): no device with that property: property match &apos;XRANDR_name&apos;=&apos;unknown&apos; does not exist (cd_window_error, 0)
Aborted (core dumped)
[tkloczko@domek libcolord-gtk]$ gdb /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test
<font color="#CD00CD"><b>GNU gdb (GDB) Fedora 8.3.50.20190501-11.fc31</b></font>
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-redhat-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from <font color="#00CD00">/home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test</font>...
(gdb) r
Starting program: /home/tkloczko/rpmbuild/BUILD/colord-gtk-0.1.26/libcolord-gtk/.libs/lt-cd-self-test 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29.9000-18.fc31.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib64/libthread_db.so.1&quot;.
[New Thread 0x7ffff60f4700 (LWP 29458)]
[New Thread 0x7ffff58f3700 (LWP 29459)]
[New Thread 0x7ffff500d700 (LWP 29460)]
warning: Loadable section &quot;.note.gnu.property&quot; outside of ELF segments
[New Thread 0x7ffff480c700 (LWP 29461)]
/colord/window: **
libcolord-gtk:ERROR:cd-self-test.c:45:cd_window_get_profile_cb: assertion failed (error == NULL): no device with that property: property match &apos;XRANDR_name&apos;=&apos;unknown&apos; does not exist (cd_window_error, 0)

Thread 1 &quot;lt-cd-self-test&quot; received signal SIGABRT, Aborted.
<font color="#0000CD">0x00007ffff7e12eb5</font> in <font color="#CDCD00">raise</font> () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-26.fc31.x86_64 at-spi2-atk-2.32.0-2.1.fc31.x86_64 at-spi2-core-2.32.1-3.fc31.x86_64 atk-2.32.0-2.1.fc31.x86_64 bzip2-libs-1.0.6-30.1.fc31.x86_64 cairo-1.16.0-5.fc31.x86_64 cairo-gobject-1.16.0-5.fc31.x86_64 colord-libs-1.4.4-2.1.fc31.x86_64 dbus-glib-0.110-3.fc29.x86_64 dbus-libs-1.12.12-7.fc31.x86_64 dconf-0.32.0-2.fc31.x86_64 fontconfig-2.13.1-7.fc31.x86_64 freetype-2.10.0-2.fc31.x86_64 fribidi-1.0.5-3.fc31.x86_64 glib2-2.61.0-3.fc31.x86_64 graphite2-1.3.10-7.fc30.x86_64 gtk3-3.24.8-3.fc31.x86_64 gvfs-client-1.40.1-3.fc31.x86_64 harfbuzz-2.4.0-2.fc31.x86_64 lcms2-2.9-6.fc31.x86_64 libX11-1.6.7-4.fc31.x86_64 libXau-1.0.9-2.fc31.x86_64 libXcomposite-0.4.4-16.fc30.x86_64 libXdamage-1.1.4-16.fc30.x86_64 libXext-1.3.4-2.fc31.x86_64 libXfixes-5.0.3-9.fc30.x86_64 libXi-1.7.9-9.fc30.x86_64 libXinerama-1.1.4-3.fc30.x86_64 libXrandr-1.5.2-2.fc31.x86_64 libXrender-0.9.10-10.fc31.x86_64 libblkid-2.33.2-2.fc31.x86_64 libdatrie-0.2.9-9.fc30.x86_64 libepoxy-1.5.3-2.fc30.x86_64 libffi-3.2.1-2.1.fc31.x86_64 libgcc-9.1.1-1.fc31.x86_64 libmount-2.33.2-2.fc31.x86_64 libselinux-2.9-1.fc31.x86_64 libuuid-2.33.2-2.fc31.x86_64 libwayland-egl-1.17.0-2.fc31.x86_64 libxcb-1.13.1-3.fc31.x86_64 libxkbcommon-0.8.4-2.fc31.x86_64 libxml2-2.9.9-3.fc31.x86_64 lz4-libs-1.9.1-2.fc31.x86_64 pango-1.43.0-4.fc31.x86_64 pcre-8.43-2.fc31.x86_64 pixman-0.38.4-2.fc31.x86_64 systemd-libs-242-3.fc31.x86_64 xfconf-4.13.6-4.fc30.x86_64 xz-libs-5.2.4-6.fc31.x86_64 zlib-1.2.11-15.fc30.x86_64
(gdb) bt full
#0  <font color="#0000CD">0x00007ffff7e12eb5</font> in <font color="#CDCD00">raise</font> () at <font color="#00CD00">/lib64/libc.so.6</font>
#1  <font color="#0000CD">0x00007ffff7dfd8d5</font> in <font color="#CDCD00">abort</font> () at <font color="#00CD00">/lib64/libc.so.6</font>
#2  <font color="#0000CD">0x00007ffff7612dde</font> in <font color="#CDCD00">g_assertion_message_expr.cold</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#3  <font color="#0000CD">0x00007ffff763fc36</font> in <font color="#CDCD00">g_assertion_message_error</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#4  <font color="#0000CD">0x0000555555555658</font> in <font color="#CDCD00">cd_window_get_profile_cb</font> (source=&lt;optimized out&gt;, res=0x555555787040, user_data=&lt;optimized out&gt;) at <font color="#00CD00">cd-self-test.c</font>:45
        window = &lt;optimized out&gt;
        widget = 0x555555850330
        error = 0x5555556aa140
        profile = 0x0
        __FUNCTION__ = &quot;cd_window_get_profile_cb&quot;
#5  <font color="#0000CD">0x00007ffff6eea0c6</font> in <font color="#CDCD00">g_simple_async_result_complete</font> () at <font color="#00CD00">/lib64/libgio-2.0.so.0</font>
#6  <font color="#0000CD">0x00007ffff6eea160</font> in <font color="#CDCD00">complete_in_idle_cb</font> () at <font color="#00CD00">/lib64/libgio-2.0.so.0</font>
#7  <font color="#0000CD">0x00007ffff765fbe2</font> in <font color="#CDCD00">g_main_context_dispatch</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#8  <font color="#0000CD">0x00007ffff76617a0</font> in <font color="#CDCD00">g_main_context_iterate.isra</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#9  <font color="#0000CD">0x00007ffff7662733</font> in <font color="#CDCD00">g_main_loop_run</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#10 <font color="#0000CD">0x00007ffff79d50d1</font> in <font color="#CDCD00">gtk_dialog_run</font> () at <font color="#00CD00">/lib64/libgtk-3.so.0</font>
#11 <font color="#0000CD">0x0000555555555430</font> in <font color="#CDCD00">colord_window_func</font> () at <font color="#00CD00">cd-self-test.c</font>:82
        window = 0x55555562a520
        dialog = 0x555555850330
#12 <font color="#0000CD">0x00007ffff763ec0e</font> in <font color="#CDCD00">g_test_run_suite_internal</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#13 <font color="#0000CD">0x00007ffff763e9b4</font> in <font color="#CDCD00">g_test_run_suite_internal</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#14 <font color="#0000CD">0x00007ffff763f0fa</font> in <font color="#CDCD00">g_test_run_suite</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#15 <font color="#0000CD">0x00007ffff7642a95</font> in <font color="#CDCD00">g_test_run</font> () at <font color="#00CD00">/lib64/libglib-2.0.so.0</font>
#16 <font color="#0000CD">0x00005555555552c1</font> in <font color="#CDCD00">main</font> (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at <font color="#00CD00">cd-self-test.c</font>:132
(gdb) 
</pre>

**Comment by kloczek** [comment] 2019-05-07 17:10
Jus t in case some questions.
I'm using glib 2.61.0 build with -DG_DISABLE_ASSERT.

**Comment by hughsie** [comment] 2019-05-07 18:43
Dupe of https://github.com/hughsie/colord-gtk/issues/4

**Closed by hughsie** 2019-05-07 18:43 UTC
